### PR TITLE
fix(sdk/xverse): return a defined type for signPsbt fn

### LINKED ISSUE #5: xverse/signatures/signPsbt returns the wrong type
It returns `Promise<null>` when it should return:

```
Promise<{
  rawTxHex: string,
  psbt: {
    hex: string,
    base64: string
  }
}>
```

### PR DESCRIPTION
**Pull request by jordankzf**
`xverse/signatures/signPsbt` returns the wrong type.

It returns `Promise<null>` when it should return:

```
Promise<{
  rawTxHex: string,
  psbt: {
    hex: string,
    base64: string
  }
}>
```

This PR will initialise the return object as an empty template that corresponds to the newly added `XverseSignedPsbt` interface, instead of just null. This allows TypeScript to infer the return type correctly.

Fixes #5

### CODE REVIEW

File: packages/sdk/src/browser-wallets/xverse/signatures.ts [hunk 1]
```diff
@@ -4,8 +4,19 @@ import { InputToSign, signMessage as _signMessage, signTransaction } from "sats-
 import { Network } from "../../config/types";
 import { isXverseInstalled, XverseNetwork } from "./utils";
 
+interface XverseSignedPsbt {
+  rawTxHex: string | null;
+  psbt: { hex: string; base64: string };
+}
```
Comment (iamcrazycoder) [inline packages/sdk/src/browser-wallets/xverse/signatures.ts:10]: lint

```suggestion
interface XverseSignedPsbt {
  rawTxHex: string;
  psbt: {
    hex: string;
    base64: string;
  };
}
```

**Review by iamcrazycoder — APPROVED** [review]
utACK

Please check the non-blocking comment.

**Review by iamcrazycoder — APPROVED** [review]
utACK
